package br.com.maplebearsystem.view;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

import javax.naming.OperationNotSupportedException;

import com.jfoenix.controls.JFXButton;

import br.com.maplebearsystem.main.MapleBearSystemDesktopClient;
import br.com.maplebearsystem.view.util.FXMLResourcePathsEnum;
import br.com.maplebearsystem.view.util.FXUISetup;
import javafx.event.ActionEvent;
import javafx.scene.Node;
import javafx.scene.layout.Pane;
import javafx.scene.layout.VBox;

public class FXMLWorkOrderMenuController implements FXMLDefaultControllerInterface, Initializable {

	@FXML
	private VBox rootPane;
	@FXML
	private JFXButton btnManageWorkOrders;
	@FXML
	private JFXButton btnOpenNewBudgetOrder;
	@FXML
	private JFXButton btnOpenNewWorkOrder;
	@FXML
	private JFXButton btnOpenWorkOrderByNumber;
	@FXML
	private JFXButton btnSearchPendingBudgetOrders;
	@FXML
	private JFXButton btnSearchApprovedBudgetOrders;
	@FXML
	private JFXButton btnSearchPendingWorkOrders;
	@FXML
	private JFXButton btnSearchConcludedWorkOrders;

	private FXMLDefaultControllerInterface sourceController;
	private Pane parentPane;

	@Override
	public void initialize(URL location, ResourceBundle resources) {
		initUI();
	}

// SECTION Main FXMLController Methods

	public void setParentPane(Pane parentPane) {
		this.parentPane = parentPane;
	}

// ENDSECTION Main FXMLController Methods

// SECTION Data Access FXMLController Methods

// ENDSECTION Data Access FXMLController Methods

// SECTION UISetup FXMLController Methods

	private void initUI() {

	}

	@Override
	public void reset() {
		// TODO Auto-generated method stub

	}

	private void autoReloadFXML() {

		try {

			FXMLWorkOrderMenuController controller;

			if (parentPane instanceof VBox) {
				controller = FXUISetup.getInstance()
						.loadFXMLIntoVbox((VBox) parentPane, MapleBearSystemDesktopClient.class,
								FXMLResourcePathsEnum.FXML_DWOR_WORKORDERMENU.getPath())
						.<FXMLWorkOrderMenuController>getController();
			} else {
				controller = FXUISetup.getInstance()
						.loadFXMLIntoPane(parentPane, MapleBearSystemDesktopClient.class,
								FXMLResourcePathsEnum.FXML_DWOR_WORKORDERMENU.getPath())
						.<FXMLWorkOrderMenuController>getController();
			}
			
			controller.setSourceFXMLController(sourceController);
			controller.setParentPane(parentPane);

		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

// ENDSECTION UISetup FXMLController Methods

	@FXML
	public void actManageWorkOrders(ActionEvent event) {
		// TODO Autogenerated
	}

	@FXML
	public void actOpenNewBudgetOrder(ActionEvent event) {
		try {
			FXMLWorkOrderEditor controller = FXUISetup.getInstance()
					.loadFXMLIntoVbox((VBox) rootPane.getParent(), MapleBearSystemDesktopClient.class,
							FXMLResourcePathsEnum.FXML_DWOR_WORKORDEREDITOR.getPath())
					.<FXMLWorkOrderEditor>getController();

			controller.setSourceFXMLController(this);

		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	@FXML
	public void actOpenNewWorkOrder(ActionEvent event) {
		try {
			FXMLWorkOrderEditor controller = FXUISetup.getInstance()
					.loadFXMLIntoVbox((VBox) rootPane.getParent(), MapleBearSystemDesktopClient.class,
							FXMLResourcePathsEnum.FXML_DWOR_WORKORDEREDITOR.getPath())
					.<FXMLWorkOrderEditor>getController();

			controller.setSourceFXMLController(this);
			controller.setHomeFXMLController(sourceController);

			((FXMLDworHomeController) sourceController).hideSidebar(true);

		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	@FXML
	public void actOpenWorkOrderByNumber(ActionEvent event) {
		// TODO Autogenerated
	}

	@FXML
	public void actSearchPendingBudgetOrders(ActionEvent event) {
		// TODO Autogenerated
	}

	@FXML
	public void actSearchApprovedBudgetOrders(ActionEvent event) {
		// TODO Autogenerated
	}

	@FXML
	public void actSearchPendingWorkOrders(ActionEvent event) {
		// TODO Autogenerated
	}

	@FXML
	public void actSearchConcludedWorkOrders(ActionEvent event) {
		// TODO Autogenerated
	}

// SECTION FXML Event Methods

// ENDSECTION FXML Event Methods

// SECTION FXMLDefaultControllerInterface Implementation

	@Override
	public void setSourceFXMLController(FXMLDefaultControllerInterface controller) throws Exception {
		sourceController = controller;
	}

	@Override
	public void setTargetFXMLController(FXMLDefaultControllerInterface controller) throws Exception {
		throw new OperationNotSupportedException("Not implemented");
	}

	@Override
	public void receiveData(Object data, FXMLDefaultControllerInterface sender) throws Exception {
		throw new OperationNotSupportedException("Not implemented");
	}

	@Override
	public void closeSenderNode(FXMLDefaultControllerInterface sender) throws Exception {
		if (sender instanceof FXMLWorkOrderEditor) {
			if (sourceController instanceof FXMLDworHomeController)
				((FXMLDworHomeController) sourceController).hideSidebar(false);
			autoReloadFXML();
		}
	}

	// ENDSECTION FXMLDefaultControllerInterface Implementation

}
